# This is a basic workflow to help you get started with Actions

name: Fetch Config

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/5 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Fetch Config
        run: curl https://docs.renovatebot.com/renovate-schema.json -o schema.json

      - name: Add Files to Git
        run: git add .

      - name: Configure User
        run: |
          git config --local user.email "mirror@wafflepowered.com"
          git config --local user.name "mokiy-actions[bot]"
      - name: Commit Changes
        run: |
          echo -e ".gitignore\ncommit.sh" > .gitignore
          echo -e "git commit -m \"chore: Update Renovate Schema\" -a\nexit 0" > commit.sh
          chmod +x commit.sh
          ./commit.sh
          rm commit.sh
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
